name = "Aglaus"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_aglaus/blob/master/LICENSE.md"
description = "Theme for Hugo that supports the Accelerated Mobile Pages Project(AMP)."
homepage = "https://github.com/dim0627/hugo_theme_aglaus"
tags = ["blog", "amp"]
features = ["amp", "responsive", "seo", "thumbnail", "share button", "structured data", "ogp", "twitter cards"]
min_version = 0.16

[author]
  name = "Daisuke Tsuji"
  homepage = "https://yet.unresolved.xyz/"

